version: '3.8'

services:
  app:
    container_name: phone-combinations-app
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "4000:3000"

